export const en = {
  searchPlaceholder: "Search by: Name, Address, Title...",
  topics: "Topics",
  time: "Time",
  location: "Location",
  language: "Language",
  map: "Map",
  list: "List",
  filterBy: "Filter by",
  clear: "Clear selection",
  apply: "Apply",
  friday: "Friday",
  saturday: "Saturday",
  israel: "Israel",
  restOfTheWorld: "Rest of the world",
  hebrew: "Hebrew",
  english: "English",
  broadcastEnded: "Broadcast ended",
  broadcasting: "Broadcasting now",
  online: "Online",
  shareEvent: "Share event",
  addToCalendar: "Add to calendar",
  followMe: "Follow me",
  close: "Close",
  share: "Share",
  broadcastError: "An error occurred while loading the live broadcast. Please try again later.",
  broadcastEndedRefraim: "The live broadcast has ended. To watch the video, please go to",
  youTubeChannel: "Our YouTube channel",
  filterDrawerBy: "Filter drawer by",
  filterButtonBy: "Filter button by",
};
