export const he = {
  searchPlaceholder: "חיפוש לפי: שם, כתובת, כותרת...",
  topics: "נושאי שיחה",
  time: "זמן",
  location: "מיקום",
  language: "שפת הרצאה",
  map: "מפה",
  list: "רשימה",
  filterBy: " סינון לפי",
  clear: "נקה בחירה",
  apply: "אישור",
  friday: "יום שישי",
  saturday: "יום שבת",
  israel: "ישראל",
  restOfTheWorld: "שאר העולם",
  hebrew: "עברית",
  english: "אנגלית",
  broadcastEnded: "השידור הסתיים",
  broadcasting: "משודר כעת",
  online: "מקוון",
  shareEvent: "שיתוף אירוע",
  addToCalendar: "הוספה ליומן",
  followMe: "עקבו אחריי",
  close: "סגור",
  share: "שיתוף",
  broadcastError: "אירעה שגיאה בטעינת השידור החי. אנא נסו שוב מאוחר יותר.",
  broadcastEndedRefraim: "השידור החי הסתיים. לצפייה בוידאו, אנא עברו ל",
  youTubeChannel: "ערוץ היוטיוב שלנו",
  filterDrawerBy: "חלון סינון אירועים לפי",
  filterButtonBy: "כפתור סינון לפי",
  // lecturer: "מרצה",
  // tags: "תגיות",
  // description: "תיאור",
  // follow: "עקוב",
  // eventDetails: "פרטי האירוע",
  // eventNotFound: "אירוע לא נמצא",
  // noEventsFound: "לא נמצאו אירועים",
  // event: "אירוע",
  // events: "אירועים",
  // allEvents: "כל האירועים",
  // all: "הכל",
  // noEvents: "אין אירועים",
  // noEventsMessage: "לא נמצאו אירועים בקטגוריה זו",
  // noEventsMessage2: "אנא נסו לשנות את הסינון",
  // noEventsMessage3: "או לחפש אירועים אחרים",
  // noEventsMessage7: "אין אירועים במיקום זה",
  // noEventsMessage10: "אין אירועים בשפה זו",
  // noEventsMessage16: "אין אירועים בזמן זה",
  // copyLink: "העתק קישור",
  // facebook: "פייסבוק",
  // instagram: "אינסטגרם",
  // twitter: "טוויטר",
  // whatsapp: "וואטסאפ",
};
