export const he = {
  searchPlaceholder: "חיפוש לפי: שם, כתובת, כותרת...",
  topics: "נושאי שיחה",
  time: "זמן",
  location: "מיקום",
  language: "שפת הרצאה",
  map: "מפה",
  list: "רשימה",
  filterBy: " סינון לפי",
  clear: "נקה בחירה",
  apply: "אישור",
  friday: "יום שישי",
  saturday: "יום שבת",
  israel: "ישראל",
  restOfTheWorld: "שאר העולם",
  hebrew: "עברית",
  english: "אנגלית",
};
